dir_in: vignette/input # input directory
dir_out: vignette/output # output directory
dir_tmp: vignette/tmp # tmp directory for intermediate files
dir_logs: vignette/logs # log files directory
cmd_file: prep_riboviz.sh # File to log bash commands
rRNA_fasta: vignette/input/yeast_rRNA_R64-1-1.fa # rRNA file to avoid aligning to
orf_fasta: vignette/input/yeast_YAL_CDS_w_250utrs.fa # orf file to align to
orf_gff_file: vignette/input/yeast_YAL_CDS_w_250utrs.gff3 # GFF2/GFF3 file for ORFs
aligner: hisat2 # short read aligner to use. Currently only hisat2 works
build_indices: TRUE # build indices for aligner? if TRUE, remake indices from fasta files
make_bedgraph: TRUE # output bedgraph.gzs of data, in addition to h5?
dir_index: vignette/index # directory to put built indices in
rRNA_index: yeast_rRNA # rRNA index file prefix, relative to dir_index
orf_index: YAL_CDS_w_250 # ORF index file prefix, relative to dir_index
fq_files: # fastq files to be processed, relative to dir_in
  WTnone: SRR1042855_s1mi.fastq.gz
  WT3AT: SRR1042864_s1mi.fastq.gz
  NotHere: example_missing_file.fastq.gz # prepRiboviz should give error message for missing files
adapters: CTGTAGGCACC # Illumina sequencing adapter(s) to remove
nprocesses: 1 # number of processes to parallelize over
MinReadLen: 10 # Minimum read length in H5 output
MaxReadLen: 50 # Maximum read length in H5 output
Buffer: 250 # Length of flanking region around the CDS
PrimaryID: Name # Primary gene IDs to access the data (YAL001C, YAL003W, etc.)
SecondID: NULL # Secondary gene IDs to access the data (COX1, EFB1, etc.)
dataset: vignette # Name of the dataset
StopInCDS: FALSE # Are stop codons part of the CDS annotations in GFF?
isTestRun: FALSE # Is this a test run
rpf: TRUE # Is the dataset an RPF or mRNA dataset?
ribovizGFF: TRUE # Does the GFF file contain 3 elements per gene - UTR5, CDS, and UTR3
features_file: NULL # file of features to correlate with ORFs
do_pos_sp_nt_freq: FALSE # Do calculate position-specific nucleotide freqeuency
t_rna: NULL # tRNA estimates
codon_pos: NULL # Codon positions in each gene
